import type { MessageUsage, ModelParams, UrlCitation } from '@shared/types/domain'
import { anthropicModelProfile, hasAnthropicThinkingBudgetConflict } from '@shared/util/anthropic'
import { effectiveReasoningEffort } from '@shared/util/reasoning'
import { effectiveWebSearchEnabled } from '@shared/util/searchTools'
import type { models } from '../db/schema'
import {
  MAX_GENERATED_IMAGE_CONTEXT_ITEMS,
  type PathMessage,
  type ResolvedAttachment,
} from './context'
import { isPlainObject, mergeDeep } from './params'

type ModelRow = typeof models.$inferSelect

export type AnthropicContentBlock = Record<string, unknown>

export interface AnthropicMessage {
  role: 'user' | 'assistant'
  content: AnthropicContentBlock[]
}

export interface AnthropicUsage {
  input_tokens?: number
  cache_creation_input_tokens?: number
  cache_read_input_tokens?: number
  output_tokens?: number
  output_tokens_details?: { thinking_tokens?: number }
}

function dataUrlPayload(dataUrl: string): { mediaType: string; data: string } {
  const match = /^data:([^;,]+);base64,(.+)$/s.exec(dataUrl)
  if (!match) throw new Error('附件不是有效的 base64 data URL')
  return { mediaType: match[1]!, data: match[2]! }
}

function textFromDataUrl(dataUrl: string): string {
  return Buffer.from(dataUrlPayload(dataUrl).data, 'base64').toString('utf8')
}

function userAttachmentBlock(
  part: Extract<PathMessage['content'][number], { type: 'input_image' | 'input_file' }>,
  attachment: ResolvedAttachment,
): AnthropicContentBlock {
  const payload = dataUrlPayload(attachment.dataUrl)
  if (part.type === 'input_image') {
    return {
      type: 'image',
      source: { type: 'base64', media_type: payload.mediaType, data: payload.data },
    }
  }
  if (attachment.mime === 'application/pdf') {
    return {
      type: 'document',
      source: { type: 'base64', media_type: 'application/pdf', data: payload.data },
      title: attachment.filename,
    }
  }
  if (attachment.mime.startsWith('text/')) {
    return {
      type: 'document',
      source: { type: 'text', media_type: 'text/plain', data: textFromDataUrl(attachment.dataUrl) },
      title: attachment.filename,
    }
  }
  throw new Error(`Anthropic Messages 不支持文件类型：${attachment.filename}`)
}

/** 把本站分支路径转换为 Anthropic Messages 的 user/assistant content blocks。 */
export function buildAnthropicMessages(
  messages: PathMessage[],
  attachments?: Map<string, ResolvedAttachment>,
): AnthropicMessage[] {
  const resolvedAttachments = attachments ?? new Map<string, ResolvedAttachment>()
  const generatedImageIds = messages
    .flatMap((message) =>
      message.content
        .filter((part) => part.type === 'image_result')
        .map((part) => part.attachment_id),
    )
    .slice(-MAX_GENERATED_IMAGE_CONTEXT_ITEMS)
  const generatedImageIdSet = new Set(generatedImageIds)
  const output: AnthropicMessage[] = []

  for (const message of messages) {
    if (message.role === 'system') continue
    if (message.role === 'assistant') {
      const content =
        message.anthropicContent ??
        message.content
          .filter((part) => part.type === 'output_text')
          .map((part) => ({ type: 'text', text: part.text }))
      if (content.length > 0) output.push({ role: 'assistant', content })

      const generatedImages = message.content.filter(
        (part): part is Extract<PathMessage['content'][number], { type: 'image_result' }> =>
          part.type === 'image_result' && generatedImageIdSet.has(part.attachment_id),
      )
      if (generatedImages.length > 0) {
        const imageContext: AnthropicContentBlock[] = [
          {
            type: 'text',
            text: 'Context: The following image was generated by the assistant earlier in this conversation. Treat it as visual context for subsequent user requests.',
          },
        ]
        for (const part of generatedImages) {
          const attachment = resolvedAttachments.get(part.attachment_id)
          if (attachment)
            imageContext.push(
              userAttachmentBlock(
                { type: 'input_image', attachment_id: part.attachment_id },
                attachment,
              ),
            )
        }
        if (imageContext.length > 1) output.push({ role: 'user', content: imageContext })
      }
      continue
    }

    const content: AnthropicContentBlock[] = []
    if (message.runtimeContext) content.push({ type: 'text', text: message.runtimeContext })
    for (const part of message.content) {
      if (part.type === 'input_text') {
        content.push({ type: 'text', text: part.text })
      } else if (part.type === 'input_image' || part.type === 'input_file') {
        const attachment = resolvedAttachments.get(part.attachment_id)
        if (attachment) content.push(userAttachmentBlock(part, attachment))
      }
    }
    if (content.length > 0) output.push({ role: 'user', content })
  }
  return output
}

function isAnthropicWebSearchTool(tool: unknown): tool is Record<string, unknown> {
  return isPlainObject(tool) && typeof tool.type === 'string' && tool.type.startsWith('web_search_')
}

function buildAnthropicTools(
  enabled: boolean,
  configuredTools: unknown,
): Record<string, unknown>[] | undefined {
  if (!Array.isArray(configuredTools)) return undefined
  if (configuredTools.length === 0) return []

  const otherTools = configuredTools.filter((tool) => !isAnthropicWebSearchTool(tool))
  if (!enabled) return otherTools.length > 0 ? otherTools.filter(isPlainObject) : undefined

  const configuredSearch = configuredTools.find(isAnthropicWebSearchTool)
  return [...(configuredSearch ? [configuredSearch] : []), ...otherTools].filter(isPlainObject)
}

export interface BuildAnthropicBodyOptions {
  model: ModelRow
  messages: AnthropicMessage[]
  instructions: string | null
  userParams?: ModelParams | null
  stream: boolean
}

/**
 * 构建 /v1/messages 请求。协议必需字段和用户动态选择由应用生成；`max_tokens` 来自可见的
 * 默认参数，其余静态模板取自高级 JSON。thinking 与 web_search 条目由对应开关决定是否下发。
 */
export function buildAnthropicBody(options: BuildAnthropicBodyOptions): Record<string, unknown> {
  const { model, messages, instructions, userParams, stream } = options
  const defaults = model.defaultParams ?? {}
  const hardParams = isPlainObject(model.hardParams) ? model.hardParams : {}
  const body: Record<string, unknown> = { model: model.modelId, messages, stream }
  if (instructions) body.system = instructions

  const profile = anthropicModelProfile(model.modelId)
  const effort = effectiveReasoningEffort(model, userParams)
  let thinkingEnabled = false
  if (model.capabilities.reasoning) {
    if (!effort || effort === 'none') {
      if (profile.thinkingDefaultsOn && profile.canDisableThinking) {
        body.thinking = { type: 'disabled' }
      } else if (!profile.canDisableThinking && isPlainObject(hardParams.thinking)) {
        body.thinking = hardParams.thinking
        thinkingEnabled = hardParams.thinking.type !== 'disabled'
      }
    } else if (isPlainObject(hardParams.thinking)) {
      body.thinking = hardParams.thinking
      thinkingEnabled = hardParams.thinking.type !== 'disabled'
    }
    if (effort && effort !== 'none' && effort !== 'enabled') {
      body.output_config = { effort }
    }
  } else if (profile.thinkingDefaultsOn && profile.canDisableThinking) {
    // Sonnet 5 等型号省略 thinking 代表默认开启；能力开关关闭时必须显式关闭。
    body.thinking = { type: 'disabled' }
  } else if (
    profile.thinkingDefaultsOn &&
    !profile.canDisableThinking &&
    isPlainObject(hardParams.thinking)
  ) {
    // 始终思考的型号不能关闭；保留可见模板才能收到 summarized thinking。
    body.thinking = hardParams.thinking
    thinkingEnabled = hardParams.thinking.type !== 'disabled'
  }

  // 新型号始终拒绝非默认采样；旧型号在 thinking 开启时也有限制。高级 JSON 仍可显式覆盖。
  if (!profile.rejectsNonDefaultSampling && !thinkingEnabled) {
    const temperature = userParams?.temperature ?? defaults.temperature
    if (temperature !== undefined) body.temperature = temperature
    const topP = userParams?.top_p ?? defaults.top_p
    if (topP !== undefined) body.top_p = topP
  }

  const maxTokens = userParams?.max_output_tokens ?? defaults.max_output_tokens
  if (maxTokens !== undefined) body.max_tokens = maxTokens

  const hardParamsWithoutManagedFields = { ...hardParams }
  delete hardParamsWithoutManagedFields.thinking
  delete hardParamsWithoutManagedFields.tools
  mergeDeep(body, hardParamsWithoutManagedFields)

  const tools = buildAnthropicTools(effectiveWebSearchEnabled(model, userParams), hardParams.tools)
  if (tools) body.tools = tools
  if (typeof body.max_tokens !== 'number') {
    throw new Error('Anthropic Messages API 必须配置 max_output_tokens（请求字段 max_tokens）')
  }
  if (hasAnthropicThinkingBudgetConflict(body.max_tokens, body.thinking)) {
    throw new Error('Anthropic thinking.budget_tokens 必须小于最终 max_tokens')
  }
  return body
}

/** Anthropic usage 已把 thinking 算入 output_tokens，reasoningTokens 只作观测分解。 */
export function mapAnthropicUsage(usage: AnthropicUsage | null | undefined): MessageUsage {
  const inputTokens = usage?.input_tokens ?? 0
  const cacheWriteTokens = usage?.cache_creation_input_tokens ?? 0
  const cachedTokens = usage?.cache_read_input_tokens ?? 0
  const outputTokens = usage?.output_tokens ?? 0
  return {
    inputTokens: inputTokens + cacheWriteTokens + cachedTokens,
    cacheWriteTokens,
    cachedTokens,
    outputTokens,
    reasoningTokens: usage?.output_tokens_details?.thinking_tokens ?? 0,
    totalTokens: inputTokens + cacheWriteTokens + cachedTokens + outputTokens,
  }
}

export function addMessageUsage(left: MessageUsage, right: MessageUsage): MessageUsage {
  return {
    inputTokens: left.inputTokens + right.inputTokens,
    cacheWriteTokens: left.cacheWriteTokens + right.cacheWriteTokens,
    cachedTokens: left.cachedTokens + right.cachedTokens,
    outputTokens: left.outputTokens + right.outputTokens,
    reasoningTokens: left.reasoningTokens + right.reasoningTokens,
    totalTokens: left.totalTokens + right.totalTokens,
  }
}

export function anthropicCitation(
  citation: unknown,
  startIndex: number,
  endIndex: number,
): UrlCitation | null {
  if (!isPlainObject(citation) || typeof citation.url !== 'string') return null
  return {
    type: 'url_citation',
    url: citation.url,
    title: typeof citation.title === 'string' ? citation.title : citation.url,
    start_index: startIndex,
    end_index: endIndex,
  }
}
