import { describe, expect, it } from 'vitest'
import { buildInput } from './context'

describe('buildInput', () => {
  it('emits a virtual system runtime context immediately before its user message', () => {
    const input = buildInput([
      {
        role: 'user',
        runtimeContext: '<runtime_context>first</runtime_context>',
        content: [{ type: 'input_text', text: 'hello' }],
      },
      {
        role: 'assistant',
        content: [{ type: 'output_text', text: 'hi' }],
      },
      {
        role: 'user',
        runtimeContext: '<runtime_context>second</runtime_context>',
        content: [{ type: 'input_text', text: 'again' }],
      },
    ])

    expect(input).toEqual([
      {
        type: 'message',
        role: 'system',
        content: [{ type: 'input_text', text: '<runtime_context>first</runtime_context>' }],
      },
      {
        type: 'message',
        role: 'user',
        content: [{ type: 'input_text', text: 'hello' }],
      },
      {
        type: 'message',
        role: 'assistant',
        status: 'completed',
        content: [{ type: 'output_text', text: 'hi', annotations: [] }],
      },
      {
        type: 'message',
        role: 'system',
        content: [{ type: 'input_text', text: '<runtime_context>second</runtime_context>' }],
      },
      {
        type: 'message',
        role: 'user',
        content: [{ type: 'input_text', text: 'again' }],
      },
    ])
  })

  it('does not invent runtime context for legacy messages', () => {
    expect(
      buildInput([{ role: 'user', content: [{ type: 'input_text', text: 'legacy' }] }]),
    ).toEqual([
      {
        type: 'message',
        role: 'user',
        content: [{ type: 'input_text', text: 'legacy' }],
      },
    ])
  })

  it('replays reasoning items verbatim before their assistant message', () => {
    const reasoningItems = [
      {
        id: 'reasoning-1',
        type: 'reasoning',
        content: [],
        encrypted_content: 'opaque-ciphertext',
        summary: [{ type: 'summary_text', text: '摘要' }],
      },
      {
        id: 'reasoning-2',
        type: 'reasoning',
        content: null,
        encrypted_content: 'opaque-ciphertext-2',
        summary: [],
      },
    ]

    const input = buildInput([
      {
        role: 'assistant',
        content: [{ type: 'output_text', text: '最终回答' }],
        reasoningItems,
      },
    ])

    expect(input).toEqual([
      ...reasoningItems,
      {
        type: 'message',
        role: 'assistant',
        status: 'completed',
        content: [{ type: 'output_text', text: '最终回答', annotations: [] }],
      },
    ])
    expect(input[0]).toBe(reasoningItems[0])
    expect(input[1]).toBe(reasoningItems[1])
  })

  it('adds assistant generated images back into the visible branch context', () => {
    const input = buildInput(
      [
        {
          role: 'assistant',
          content: [
            { type: 'output_text', text: '已生成。' },
            { type: 'image_result', attachment_id: 'generated-1' },
          ],
        },
        { role: 'user', content: [{ type: 'input_text', text: '把刚才那张图改成红色' }] },
      ],
      new Map([
        [
          'generated-1',
          {
            dataUrl: 'data:image/png;base64,abc',
            mime: 'image/png',
            filename: 'generated.png',
            kind: 'image',
          },
        ],
      ]),
    )

    expect(input).toEqual([
      {
        type: 'message',
        role: 'assistant',
        status: 'completed',
        content: [{ type: 'output_text', text: '已生成。', annotations: [] }],
      },
      {
        type: 'message',
        role: 'user',
        content: [
          {
            type: 'input_text',
            text: 'Context: The following image was generated by the assistant earlier in this conversation. Treat it as visual context for subsequent user requests.',
          },
          { type: 'input_image', detail: 'auto', image_url: 'data:image/png;base64,abc' },
        ],
      },
      {
        type: 'message',
        role: 'user',
        content: [{ type: 'input_text', text: '把刚才那张图改成红色' }],
      },
    ])
  })

  it('keeps generated-image context after replayed reasoning and assistant output', () => {
    const input = buildInput(
      [
        {
          role: 'assistant',
          reasoningItems: [
            { type: 'reasoning', id: 'reasoning-image', encrypted_content: 'cipher' },
          ],
          content: [
            { type: 'output_text', text: '已生成。' },
            { type: 'image_result', attachment_id: 'generated-replay' },
          ],
        },
      ],
      new Map([
        [
          'generated-replay',
          {
            dataUrl: 'data:image/png;base64,replay',
            mime: 'image/png',
            filename: 'generated.png',
            kind: 'image',
          },
        ],
      ]),
    )

    expect(input.map((item) => (item as { type?: string }).type)).toEqual([
      'reasoning',
      'message',
      'message',
    ])
    expect(input[2]).toMatchObject({ type: 'message', role: 'user' })
  })

  it('keeps only the most recent generated images when building image context', () => {
    const messages = Array.from({ length: 13 }, (_, index) => ({
      role: 'assistant' as const,
      content: [
        { type: 'output_text' as const, text: `image ${index}` },
        { type: 'image_result' as const, attachment_id: `generated-${index}` },
      ],
    }))
    const attachments = new Map(
      messages.map((_message, index) => [
        `generated-${index}`,
        {
          dataUrl: `data:image/png;base64,${index}`,
          mime: 'image/png',
          filename: 'generated.png',
          kind: 'image' as const,
        },
      ]),
    )

    const input = buildInput(messages, attachments)
    const serialized = JSON.stringify(input)

    expect(serialized).not.toContain('data:image/png;base64,0')
    expect(serialized).toContain('data:image/png;base64,1')
    expect(serialized).toContain('data:image/png;base64,12')
  })
})
