import type { ContentPart, Role } from '@shared/types/domain'

export interface PathMessage {
  role: Role
  content: ContentPart[]
  /** 用户消息创建时冻结的运行环境；数据库内部字段，不进入普通消息 DTO。 */
  runtimeContext?: string | null
}

export interface ResolvedAttachment {
  dataUrl: string
  mime: string
  filename: string
  kind: 'image' | 'file'
}

const MAX_GENERATED_IMAGE_CONTEXT_ITEMS = 12

function generatedImageContextIds(messages: PathMessage[]): Set<string> {
  const ids = messages.flatMap((message) =>
    message.content
      .filter((part): part is Extract<ContentPart, { type: 'image_result' }> => part.type === 'image_result')
      .map((part) => part.attachment_id),
  )
  return new Set(ids.slice(-MAX_GENERATED_IMAGE_CONTEXT_ITEMS))
}

/**
 * 由「当前分支路径」的消息构建上游 input[]（本地上下文重放，store=false）。
 * 助手历史用 output_text（annotations 置空），其最终生成图作为合成图片上下文追加。
 * 用户消息用 input_text/input_image/input_file。
 * 图片/文件在请求构建时由 attachments 映射读为内联 base64 data URL。
 */
export function buildInput(
  messages: PathMessage[],
  attachments?: Map<string, ResolvedAttachment>,
): unknown[] {
  const atts = attachments ?? new Map<string, ResolvedAttachment>()
  const generatedContextIds = generatedImageContextIds(messages)
  const items: unknown[] = []

  for (const m of messages) {
    if (m.role === 'user' && m.runtimeContext) {
      items.push({
        type: 'message',
        role: 'system',
        content: [{ type: 'input_text', text: m.runtimeContext }],
      })
    }

    if (m.role === 'assistant') {
      const text = m.content.map((p) => (p.type === 'output_text' ? p.text : '')).join('')
      items.push({
        type: 'message',
        role: 'assistant',
        status: 'completed',
        content: [{ type: 'output_text', text, annotations: [] }],
      })
      const generatedImages = m.content.filter(
        (part): part is Extract<ContentPart, { type: 'image_result' }> =>
          part.type === 'image_result' && generatedContextIds.has(part.attachment_id),
      )
      const generatedImageContent: unknown[] = [
        {
          type: 'input_text',
          text: 'Context: The following image was generated by the assistant earlier in this conversation. Treat it as visual context for subsequent user requests.',
        },
      ]
      for (const part of generatedImages) {
        const a = atts.get(part.attachment_id)
        if (a) generatedImageContent.push({ type: 'input_image', detail: 'auto', image_url: a.dataUrl })
      }
      if (generatedImageContent.length > 1) {
        items.push({ type: 'message', role: 'user', content: generatedImageContent })
      }
      continue
    }

    const content: unknown[] = []
    for (const part of m.content) {
      if (part.type === 'input_text') {
        content.push({ type: 'input_text', text: part.text })
      } else if (part.type === 'input_image') {
        const a = atts.get(part.attachment_id)
        if (a) content.push({ type: 'input_image', detail: part.detail ?? 'auto', image_url: a.dataUrl })
      } else if (part.type === 'input_file') {
        const a = atts.get(part.attachment_id)
        if (a) content.push({ type: 'input_file', filename: a.filename, file_data: a.dataUrl })
      }
    }
    if (content.length > 0) items.push({ type: 'message', role: m.role, content })
  }
  return items
}
