/**
 * 常用内置图标（策展）。
 *
 * 内置库有 900+ 个图标，一次性渲染会同时发出 900 个 SVG 请求，因此选择器默认只展示这一小撮
 * 高频品牌；要找别的就用搜索，从完整目录里过滤（结果同样有数量上限）。
 * 取色原则与自动识别一致：有官方彩色版就用彩色版，本身是单色标识的品牌用单色版。
 */
export const CURATED_ICON_SLUGS: readonly string[] = [
  // 主流对话模型
  'openai',
  'claude-color',
  'gemini-color',
  'grok',
  'deepseek-color',
  'qwen-color',
  'kimi-color',
  'zhipu-color',
  'doubao-color',
  'hunyuan-color',
  'minimax-color',
  'wenxin-color',
  'stepfun-color',
  'yi-color',
  'baichuan-color',
  'sensenova-color',
  'spark-color',
  'internlm-color',
  'ai360-color',
  'skywork-color',
  'xuanyuan-color',
  'meta-color',
  'mistral-color',
  'perplexity-color',
  'cohere-color',
  'gemma-color',
  'nova-color',
  'dbrx-color',
  'ai21',
  'upstage-color',
  'rwkv',
  // 生图 / 音视频
  'dalle-color',
  'sora-color',
  'flux',
  'stability-color',
  'midjourney',
  'ideogram',
  'recraft',
  'suno',
  'runway',
  'pika',
  'luma-color',
  'kling-color',
  'vidu-color',
  'jimeng-color',
  'viggle',
  // 厂商 / 云 / 网关
  'anthropic',
  'google-color',
  'microsoft-color',
  'azure-color',
  'nvidia-color',
  'ibm',
  'aws-color',
  'bedrock-color',
  'vertexai-color',
  'deepmind-color',
  'bytedance-color',
  'alibabacloud-color',
  'tencent-color',
  'baidu-color',
  'volcengine-color',
  'openrouter-color',
  'siliconcloud-color',
  'together-color',
  'fireworks-color',
  'groq',
  'cerebras-color',
  'novita-color',
  'ppio-color',
  'aihubmix-color',
  'burncloud-color',
  'infinigence-color',
  'ollama',
  'lmstudio',
  // 工具
  'codex-color',
  'copilot-color',
  'github',
  'jina',
  'voyage-color',
  'lobehub',
]

/** 搜索结果一次最多渲染多少个：每个格子都会发一次 SVG 请求，必须钉死上限。 */
export const ICON_SEARCH_RESULT_LIMIT = 120
